version: '2.0'

services:

  env_test:
    container_name: env_test
    image: docker.miracum.org/ketos/ketos_env_ds:v0.1.0
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "5001:5000"
    networks:
      - backend
    volumes:
      - ./ketos_environment_api/src:/mlService_dockerApi/src
      - ./ketos_environment_api/src/auth:/root/src/auth
    command: bash -c "cd /mlService_dockerApi/src && chmod +x startup.sh && ./startup.sh"

networks:
  backend:
